-- Open Brain Local: PTA (Personal Trade Assistant) Schema
-- Event-Sourcing Approach: No "State" table, only a ledger of execution events.

SET search_path = public, extensions;

-- ─────────────────────────────────────────────────────────────
-- TABLE: pta_execution_log
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pta_execution_log (
  id              BIGSERIAL PRIMARY KEY,
  trade_id        TEXT NOT NULL,        -- Generated by STM (e.g., UUID or TRD-XXX)
  ticker          TEXT NOT NULL,
  event_type      TEXT NOT NULL,        -- 'ORDER_SUBMITTED', 'FILL', 'CANCEL', 'CASH_TRANSFER'
  action          TEXT,                 -- 'BUY', 'SELL', 'DEPOSIT', 'WITHDRAW'
  quantity        NUMERIC,              -- Always positive in UI, but handled contextually. For fills: absolute amount.
  price           NUMERIC,              -- Execution price or limit price
  stop_price      NUMERIC,              -- Auxiliary price for Stop Orders
  broker_order_id TEXT,                 -- ID returned by IBKR/Broker
  commission      NUMERIC DEFAULT 0.0,
  currency        TEXT DEFAULT 'USD',   -- Trade currency (e.g., USD, EUR)
  exchange        TEXT,                 -- Exchange hint (e.g., SMART, FWB2)
  slippage        NUMERIC DEFAULT 0.0,  -- Recorded slippage on fill
  notes           TEXT,                 -- Technical execution notes (not strategy)
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pta_trade_id ON pta_execution_log (trade_id);
CREATE INDEX IF NOT EXISTS idx_pta_ticker ON pta_execution_log (ticker);
CREATE INDEX IF NOT EXISTS idx_pta_event_type ON pta_execution_log (event_type);


-- ─────────────────────────────────────────────────────────────
-- VIEW: pta_open_trades
-- ─────────────────────────────────────────────────────────────
-- Calculates the current state of trades by aggregating FILL and CASH events.
-- Net Quantity: sum of BUY fills minus sum of SELL fills.
CREATE OR REPLACE VIEW pta_active_positions AS
WITH fill_aggregation AS (
    SELECT 
        trade_id,
        ticker,
        currency,
        SUM(
            CASE 
                WHEN action IN ('BUY', 'DEPOSIT') THEN quantity 
                WHEN action IN ('SELL', 'WITHDRAW') THEN -quantity 
                ELSE 0 
            END
        ) as net_quantity,
        SUM(commission) as total_commission,
        SUM(slippage) as total_slippage,
        MIN(created_at) as open_time
    FROM pta_execution_log
    WHERE event_type = 'FILL'
    GROUP BY trade_id, ticker, currency
),
latest_stops AS (
    -- Find the most recent stop price submitted for the trade
    SELECT DISTINCT ON (trade_id) 
        trade_id, 
        stop_price as current_stop_loss
    FROM pta_execution_log
    WHERE event_type = 'ORDER_SUBMITTED' AND stop_price IS NOT NULL
    ORDER BY trade_id, created_at DESC
)
SELECT 
    f.trade_id,
    f.ticker,
    f.currency,
    f.net_quantity,
    f.total_commission,
    f.total_slippage,
    f.open_time,
    s.current_stop_loss,
    CASE 
        WHEN f.net_quantity > 0 THEN 'LONG'
        WHEN f.net_quantity < 0 THEN 'SHORT'
        ELSE 'CLOSED'
    END as position_type
FROM fill_aggregation f
LEFT JOIN latest_stops s ON f.trade_id = s.trade_id
WHERE f.net_quantity != 0; -- Only show open/active positions

-- ─────────────────────────────────────────────────────────────
-- FUNCTIONS
-- ─────────────────────────────────────────────────────────────

-- Helper to quickly log an event
CREATE OR REPLACE FUNCTION pta_log_event(
  p_trade_id TEXT,
  p_ticker TEXT,
  p_event_type TEXT,
  p_action TEXT,
  p_quantity NUMERIC DEFAULT NULL,
  p_price NUMERIC DEFAULT NULL,
  p_stop_price NUMERIC DEFAULT NULL,
  p_broker_order_id TEXT DEFAULT NULL,
  p_commission NUMERIC DEFAULT 0.0,
  p_currency TEXT DEFAULT 'USD',
  p_exchange TEXT DEFAULT NULL,
  p_slippage NUMERIC DEFAULT 0.0,
  p_notes TEXT DEFAULT NULL
)
RETURNS BIGINT AS $$
DECLARE
  v_id BIGINT;
BEGIN
  INSERT INTO pta_execution_log (
    trade_id, ticker, event_type, action, quantity, price, stop_price, 
    broker_order_id, commission, currency, exchange, slippage, notes
  ) VALUES (
    p_trade_id, p_ticker, p_event_type, p_action, p_quantity, p_price, p_stop_price, 
    p_broker_order_id, p_commission, p_currency, p_exchange, p_slippage, p_notes
  ) RETURNING id INTO v_id;
  
  RETURN v_id;
END;
$$ LANGUAGE plpgsql;

-- ─────────────────────────────────────────────────────────────
-- GRANTS
-- ─────────────────────────────────────────────────────────────
GRANT ALL ON TABLE public.pta_execution_log TO anon, service_role;
GRANT ALL ON SEQUENCE pta_execution_log_id_seq TO anon, service_role;
GRANT SELECT ON public.pta_active_positions TO anon, service_role;
GRANT EXECUTE ON FUNCTION pta_log_event TO anon, service_role;
