import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { supabase } from "./shared.ts";

export function registerPtaTools(server: McpServer) {
  // Tool: Trade (Execution Logger)
  server.registerTool(
    "trade",
    {
      title: "Trade Execution",
      description: "Log a trade execution event (ENTER, UPDATE, EXIT, CANCEL, CASH).",
      inputSchema: {
        action: z.enum(["ENTER", "UPDATE", "EXIT", "CANCEL", "CASH", "REFRESH"]).describe("The execution action"),
        trade_id: z.string().describe("The unique Trade-ID (generated by STM)"),
        ticker: z.string().describe("The stock symbol"),
        quantity: z.number().optional().describe("Amount of shares/contracts"),
        limit_price: z.number().optional().describe("Limit price for orders"),
        stop_loss: z.number().optional().describe("Stop loss price"),
        broker_order_id: z.string().optional().describe("Optional broker-provided order ID"),
        commission: z.number().optional().default(0),
        currency: z.string().optional().default("USD"),
        exchange: z.string().optional().describe("Target exchange (e.g., SMART)"),
        notes: z.string().optional().describe("Technical notes about the execution"),
      },
    },
    async (params: any) => {
      try {
        let eventType = "ORDER_SUBMITTED";
        let action = params.action;

        if (params.action === "CASH") {
            eventType = "CASH_TRANSFER";
            action = params.quantity && params.quantity > 0 ? "DEPOSIT" : "WITHDRAW";
        } else if (params.action === "EXIT") {
            action = "SELL";
        } else if (params.action === "ENTER") {
            action = "BUY";
        }

        const { data, error } = await supabase.rpc("pta_log_event", {
          p_trade_id: params.trade_id,
          p_ticker: params.ticker,
          p_event_type: eventType,
          p_action: action,
          p_quantity: Math.abs(params.quantity || 0),
          p_price: params.limit_price || null,
          p_stop_price: params.stop_loss || null,
          p_broker_order_id: params.broker_order_id || null,
          p_commission: params.commission || 0,
          p_currency: params.currency || "USD",
          p_exchange: params.exchange || null,
          p_notes: params.notes || null
        });

        if (error) throw error;

        return { 
          content: [{ 
            type: "text", 
            text: `Event logged successfully (ID: ${data}). Action: ${params.action} for ${params.ticker} (Trade: ${params.trade_id})` 
          }] 
        };
      } catch (err: any) {
        return { content: [{ type: "text", text: `Error logging trade: ${err.message}` }], isError: true };
      }
    }
  );

  // Tool: List Active Positions
  server.registerTool(
    "list_active_positions",
    {
      title: "List Active Positions",
      description: "Show all currently open trades and their net positions.",
      inputSchema: {
        ticker: z.string().optional().describe("Optional filter by ticker"),
      },
    },
    async ({ ticker }: any) => {
      try {
        let query = supabase.from("pta_active_positions").select("*");
        if (ticker) query = query.eq("ticker", ticker.toUpperCase());

        const { data, error } = await query;
        if (error) throw error;

        if (!data || data.length === 0) {
          return { content: [{ type: "text", text: "No active positions found." }] };
        }

        const report = data.map((p: any) => 
          `[${p.trade_id}] ${p.ticker}: ${p.net_quantity} @ ${p.position_type} (SL: ${p.current_stop_loss || 'NONE'})`
        ).join("\n");

        return { content: [{ type: "text", text: report }] };
      } catch (err: any) {
        return { content: [{ type: "text", text: `Error fetching positions: ${err.message}` }], isError: true };
      }
    }
  );

  // Tool: Get Trade History
  server.registerTool(
    "get_trade_history",
    {
      title: "Get Trade History",
      description: "Retrieve all execution events for a specific trade ID.",
      inputSchema: {
        trade_id: z.string().describe("The Trade-ID to look up"),
      },
    },
    async ({ trade_id }: any) => {
      try {
        const { data, error } = await supabase
          .from("pta_execution_log")
          .select("*")
          .eq("trade_id", trade_id)
          .order("created_at", { ascending: true });

        if (error) throw error;
        if (!data || data.length === 0) {
          return { content: [{ type: "text", text: `No history found for Trade-ID: ${trade_id}` }] };
        }

        const history = data.map((e: any) => 
          `${new Date(e.created_at).toLocaleString()} | ${e.event_type} | ${e.action} | Qty: ${e.quantity} | Price: ${e.price || '-'} | OID: ${e.broker_order_id || '-'}`
        ).join("\n");

        return { content: [{ type: "text", text: `History for ${trade_id}:\n\n${history}` }] };
      } catch (err: any) {
        return { content: [{ type: "text", text: `Error fetching history: ${err.message}` }], isError: true };
      }
    }
  );
}
